### ISSUE TITLE
The problem of Maven error reporting when downloading this item

### ISSUE THREAD

**Issue by OverrideSkywalker** [AlmasB/Zephyria#1]
When I download this project,Import it into my eclipse
two errors tips:

> Plugin execution not covered by lifecycle configuration: org.jetbrains.kotlin:kotlin-maven-plugin:1.0.5:compile (execution: compile, phase: process-sources)
> Plugin execution not covered by lifecycle configuration: org.jetbrains.kotlin:kotlin-maven-plugin:1.0.5:test-compile (execution: test-compile, phase: process-test-sources)

Does the two jar exist?Or is China's network firewall shielding this jar?
Now,My eclipse reminds me that I'm missing `com.almasb.zeph.*`
Can you send this package to me?Thank you very much.

**Comment by AlmasB** [comment]
As the project uses Java and Kotlin, I'd recommend that you use IntelliJ IDEA or build the project with `mvn package` from the command line. I'm positive that both approaches work. I cannot guarantee you can build the project in Eclipse

**Comment by OverrideSkywalker** [comment]
Yes, I run perfectly on IntelliJ IDEA,Thank you very much.
