### ISSUE TITLE
Building with mvn package, no manifest when running java -jar

### ISSUE THREAD

**Issue by herve-ch** [AlmasB/Zephyria#2]
Hello when i build with maven mvm package then try to run java - jar, error shows up with no manifest found for main class

**Comment by AlmasB** [comment]
Thanks, I'll update the README. The instructions now are:

### Run

```
mvn javafx:run
```

### Package

```
mvn javafx:jlink
```

Please can you let me know if these work

**Comment by herve-ch** [comment]
Yes thanks, it works with these new instructions!

Thanks a lot
________________________________
De : Almas Baimagambetov <notifications@github.com>
Envoyé : jeudi 28 janvier 2021 07:23
À : AlmasB/Zephyria <Zephyria@noreply.github.com>
Cc : herve-ch <rv_changue@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [AlmasB/Zephyria] Building with mvn package, no manifest when running java -jar (#2)


Thanks, I'll update the README. The instructions now are:

Run

mvn javafx:run


Package

mvn javafx:jlink


Please can you let me know if these work
