### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by sproket** [AlmasB/Zephyria#3]
These are occurring when I cloned and then opened the project in IntelliJ 2020.3 with JDK 15.0.1

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil

Eventually it fails in ZephFactory import com.almasb.fxgl.pathfinding.Cell with Unresolved reference: Cell

**Comment by AlmasB** [comment]
Thanks, compilation should be fixed now

**Comment by sproket** [comment]
Thanks!
